// @generated by corpus/paired-build/the round/work/the generator — do not edit.
// Constants of analysis_geometry_builder read from the paired build read-only data
// (f32.py provenance table; carrier VA noted per item).

// f64 constants as bit patterns (dbl_*)
pub const LOG2E_BITS: u64 = 0x3ff7154760000000; // paired_log2e
pub const PSYCHO_BITS: u64 = 0x4017dcf680000000; // paired_psycho
pub const LN2_BITS: u64 = 0x3fe62e42a0000000; // paired_ln2
pub const HALF_BITS: u64 = 0x3fe0000000000000; // paired_half
pub const QUARTER_BITS: u64 = 0x3fd0000000000000; // paired_quarter
pub const ATH_OFF_BITS: u64 = 0x4059000000000000; // paired_ath_offset
pub const TWO_BITS: u64 = 0x4000000000000000; // paired_two
pub const EIGHTH_BITS: u64 = 0x3fc0000000000000; // 0x100163xx immediate-scale 0.125

// paired_ath_source_curve: ATH source curve, 88 f32 bit patterns (the build's code + entry*4)
pub const paired_ath_source_curve: &[u32] = &[
    0xc1f80000, 0xc2040000, 0xc20c0000, 0xc2140000, 0xc21c0000, 0xc2240000, 0xc22c0000, 0xc2340000,
    0xc23c0000, 0xc2440000, 0xc24c0000, 0xc2540000, 0xc25c0000, 0xc2640000, 0xc26c0000, 0xc2740000,
    0xc27c0000, 0xc2820000, 0xc2860000, 0xc28a0000, 0xc28e0000, 0xc2920000, 0xc2960000, 0xc29a0000,
    0xc29e0000, 0xc2a20000, 0xc2a60000, 0xc2a80000, 0xc2aa0000, 0xc2ac0000, 0xc2ae0000, 0xc2b00000,
    0xc2b20000, 0xc2b40000, 0xc2b60000, 0xc2b80000, 0xc2ba0000, 0xc2bc0000, 0xc2be0000, 0xc2c00000,
    0xc2c00000, 0xc2c20000, 0xc2c20000, 0xc2c20000, 0xc2c40000, 0xc2c40000, 0xc2c40000, 0xc2c60000,
    0xc2c40000, 0xc2c20000, 0xc2c20000, 0xc2c40000, 0xc2c60000, 0xc2c80000, 0xc2ca0000, 0xc2ca0000,
    0xc2cc0000, 0xc2ce0000, 0xc2d00000, 0xc2d20000, 0xc2d40000, 0xc2d40000, 0xc2d60000, 0xc2d60000,
    0xc2d20000, 0xc2d00000, 0xc2ce0000, 0xc2cc0000, 0xc2ca0000, 0xc2c60000, 0xc2c40000, 0xc2c20000,
    0xc2c00000, 0xc2be0000, 0xc2be0000, 0xc2c00000, 0xc2c20000, 0xc2c20000, 0xc2ba0000, 0xc2b20000,
    0xc2a00000, 0xc28c0000, 0xc2480000, 0xc2200000, 0xc1f00000, 0xc1d00000, 0xc1b00000, 0xc1900000,
];
